beta-blog/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get 'about', to: 'pages#about'

  resources :articles
  

  get 'signup', to: "users#new"
  post 'users', to: 'users#create'
  resources :users, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :categories, except: [:destroy]
end

beta-blog/app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  validates :title, presence: true, length: { minimum: 3, maximum: 50 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
  validates :user_id, presence: true
end

beta-blog/app/models/category.rb
class Category < ActiveRecord::Base
    validates :name, presence: true, length: {minimum: 3, maximum: 25}, uniqueness: { case_sensitive: false }
end

beta-blog/app/models/user.rb
class User < ApplicationRecord
    has_many :articles, dependent: :destroy
    before_save { self.email = email.downcase }
    validates :username, presence: true, 
    uniqueness: { case_sensitive: false }, 
    length: { minimum: 3, maximum: 25 }

    VALID_EMAIL_REGEX = /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i

    validates :email, presence: true, 
    length: { maximum: 105 }, 
    uniqueness: { case_sensitive: false }, 
    format: { with: VALID_EMAIL_REGEX }

    has_secure_password
end

beta-blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user #convert to boolean
  end

  def require_user
    if !logged_in?
      flash[:danger] = "You must be logged in to perform that action"
      redirect_to login_path
    end
  end
end

beta-blog/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

    before_action :set_article, only: [:edit,:update,:show,:destroy]
    before_action :require_user, except: [:index, :show ]
    before_action :require_same_user, only: [ :edit, :update, :destroy ]

    def index
        @articles = Article.paginate(page: params[:page], per_page: 5)
    end

    def new
        @article = Article.new
    end

    def edit

    end

    def create
        #render plain: params[:article].inspect
        @article = Article.new(article_params)
        @article.user = current_user
        if @article.save
            flash[:success] = "Article was successfully created"
            redirect_to article_path(@article)
        else
            render 'new'
        end
    end

    def update
        
        if @article.update(article_params)
            flash[:success] = "Article was successfully updated"
            redirect_to article_path(@article)
        else
            render 'edit'
        end
    end

    def show
        
    end

    def destroy
        
        @article.destroy
        flash[:danger] = "Article was successfully deleted."
        redirect_to articles_path
    end

    private
        def article_params
            params.require(:article).permit(:title, :description)
        end
        def set_article
            @article = Article.find(params[:id])
        end
        def require_same_user
            if current_user != @article.user and !current_user.admin?
                flash[:danger] = "You can only edit or delete your own article."
                redirect_to articles_path
            end
        end

end

beta-blog/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :require_admin, except: [:index, :show]
    def index
        @categories = Category.paginate(page: params[:page],per_page: 5)
    end

    def new
        @category = Category.new
    end

    def show

    end

    def create
        @category = Category.new(params_category)
        if @category.save
            flash[:success] = "Category was created successfully"
            redirect_to categories_path
        else
            render 'new'
        end
    end

    private
        def params_category
            params.require(:category).permit(:name)
        end
        def require_admin
            if !logged_in? || (logged_in? and !current_user.admin?)
                flash[:danger] = "You need elevated permissions to do that!"
                redirect_to categories_path
            end
        end

end
  

beta-blog/app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
        redirect_to articles_path if logged_in?
    end
    def about
    end
end
  

beta-blog/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new

    end

    def create
        user = User.find_by(email: params[:session][:email].downcase)
        if user && user.authenticate(params[:session][:password])
            session[:user_id] = user.id 
            flash.now[:success] = 'Logged in!'
            redirect_to user_path(user)
        else
            flash.now[:danger] = 'There was something wrong with your credentials.'
            render 'new'
        end
    end

    def delete

    end

    def destroy
        session[:user_id] = nil
        flash.now[:success] = 'Logged out!'
        redirect_to root_path
    end

end
  

beta-blog/app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: [:edit,:update,:show, :destroy]
    before_action :require_user, except: [:index, :show, :new, :create ]
    before_action :require_same_user, only: [:edit,:update, :destroy]
    before_action :require_admin, only: [:destroy]
    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            flash[:success] = "Welcome to Elfa Blog, #{@user.username}. "
            redirect_to user_path(@user)
        else
            render 'new'
        end
    end

    def edit

    end

    def update
        if @user.update(user_params)
            flash[:success] = "User was successfully updated"
            render 'edit'
        else
            render 'edit'
        end
    end

    def show
        
        @articles = @user.articles.paginate(page: params[:page], per_page: 5)
    end

    def destroy
        @user.destroy
        flash[:danger] = "User and all related articles have been destroyed."
        redirect_to users_path
    end

    def index
        @users = User.paginate(page: params[:page], per_page: 5)
        
    end

    private
        def user_params
            params.require(:user).permit(:username, :email, :password)
        end
        def set_user
            @user = User.find(params[:id])
        end
        def require_same_user
            if current_user != @user and !current_user.admin?
                flash[:danger] = "You can only edit yourself!"
                redirect_to root_path
            end
        end
        def require_admin
            if logged_in? and !current_user.admin?
                flash[:danger] = "You need elevated permissions to do that!"
                redirect_to root_path
            end
        end
end
  

beta-blog/app/helpers/application_helper.rb
module ApplicationHelper

    def gravatar_for(user, options = { size: 80 })
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        size = options[:size]
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
        image_tag(gravatar_url, alt: user.username, class: "img-circle")
    end

end

beta-blog/app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>
<div class="row">
  <div class="col-xs-12">
    <%= form_for @article, :html => {class: "form-horizontal", role: "form"} do |f| %>
    <div class="form-group">
      <div class="control-label col-sm-2">
      
        <%= f.label :title %><br />
      </div>
      <div class="col-sm-10">
          <%= f.text_field :title, class: "form-control", placeholder: "Title of article", autofocus: true %>
      </div>
     </div>
     <div class="form-group">
        <div class="control-label col-sm-2">
            <%= f.label :description %>
        </div>
        <div class="col-sm-10">
            <%= f.text_area :description, rows: 10,  class: "form-control", placeholder: "Body of article" %>
        </div>
      </div>
        
      <div class="form-group">
        <div class="col-sm-10 center">
          <%= f.submit class: "btn btn-primary btn-lg" %>
        </div>
      </div>
    </div>
  </div>

    <% end %>
  <div class="col-xs-4 col-xs-offset-4">
    [<%= link_to "Cancel and go back to all Articles", articles_path %>]
  </div>
  </div>
</div>

beta-blog/app/views/articles/edit.html.erb
<h1 align="center">Edit existing article</h1>

<%= render 'form' %>

beta-blog/app/views/articles/index.html.erb
<h1 align="center">Listing all articles</h1>
<div align="center">
    <%= will_paginate %>
</div>
<%= render 'shared/article' %>
<div align="center">
    <%= will_paginate %>
</div>

beta-blog/app/views/articles/new.html.erb
<h1 align="center">Create an Article</h1>

<%= render 'form' %>

beta-blog/app/views/articles/show.html.erb
<h2 align="center"><%= @article.title %></h2>
<hr>
<div class="well col-xs-8 col-xs-offset-2">
    <div class="row">
        <div class="col-xs-8 col-xs-offset-2">
            <div class="well well-lg">
                <div class="user-img">
                    <%= link_to gravatar_for(@article.user), user_path(@article.user) %>
                </div>
                <div class="user-title">
                    <%= link_to truncate(@article.user.username, length: 15), user_path(@article.user) %>
                </div>
                <hr>
                <small><%= pluralize(@article.user.articles.count, "article") if @article.user.articles %></small>
            </div>
        </div>
    </div>
    <div class="center description">
        <%= simple_format(@article.description) %>
    </div>
    <% if logged_in? && (current_user == article.user || current_user.admin? )  %>
        <div class="article-actions">
            <%= link_to "Edit", edit_article_path(@article), class: "btn btn-xs btn-primary" %>
            <%= link_to "Delete", article_path(@article), method: :delete, data: {confirm: "Are you sure!?"}, class: "btn btn-xs btn-danger" %>
            <%= link_to "Back to all Articles", articles_path, class: "btn btn-xs btn-success" %>
        </div>
    <% end %>
</div>

beta-blog/app/views/pages/about.html.erb
<h1>About</h1>
<%= link_to 'Home', root_path %>
<p>This is a simple rails website. Totally not cool - I know? But it may be cool one day.</p>

beta-blog/app/views/pages/home.html.erb
<div class="center jumbotron">
    <div>
        <h1>Hello World</h1>
        <%= link_to 'Beta Blog', articles_path %> | <%= link_to 'About', about_path %>
        <p>This is a simple rails website. Totally not cool - I know? But it may be cool one day.</p>
    </div>
</div>

beta-blog/app/views/pages/index.html.erb
<h1>Listing all articles</h1>
<table>
    <tr>
        <th>Title</th>
        <th>Description</th>
    </tr>
</table>
<%%>